import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "../components/Button";
import Soma from "../components/Soma";
import ReverterString from "../components/ReverterString";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Talentos App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.helloWorldText}>Hello World</h1>

        <Soma notas={[1,2,3,4,5,6,7,8,9,10]} />

        
        <ReverterString frase="João é um cara muito legal :D"/>

        <div>
          <Button texto="João" cor="blue" quandoClicar={() => console.log('cliquei no João')} />
          <Button texto="É" cor="green" quandoClicar={() => console.log('cliquei no é')} />
          <Button texto="Um cara" cor="red" quandoClicar={() => console.log("cliquei no um cara")} />
          <Button texto="Muito" cor="yellow" quandoClicar={() => console.log("cliquei no muito")} />
          <Button texto="Legal" cor="orange" quandoClicar={() => console.log("cliquei no legal")} />

          

        </div>
      </main>
    </>
  );
}
